chart:
  name: intel-device-plugins-operator
  repoURL: https://intel.github.io/helm-charts/
  targetRevision: 0.32.1  # renovate: depName=intel/intel-device-plugins-for-kubernetes extractVersion=^(?<version>.+)$
  namespace: intel-device-plugins
