apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qbit

resources:
  - gluetun-secret.yaml

helmCharts:
- name: app-template
  releaseName: qbit-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.3.0
  valuesFile: values.yaml
  namespace: qbit
