controllers:
  main:
    pod: {}
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   fsGroup: 2000
      #   fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.53.3
        env:
          TZ: Europe/Berlin
          ND_AUTHREQUESTLIMIT: 0
          ND_DATAFOLDER: /config
          ND_ENABLEGRAVATAR: true
          ND_ENABLESHARING: true
          ND_LOGLEVEL: info
          ND_MUSICFOLDER: /media
          ND_PORT: 8080
          ND_PROMETHEUS_ENABLED: true
          ND_SCANSCHEDULE: "@every 1h"
          ND_LASTFM_APIKEY: "d3fec012063079f858124f3b40a72a84"
          ND_LASTFM_SECRET: "9594cc4606cc9b2a4acc2e3d4955cd17"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
service:
  main:
    controller: main
    ports:
      http:
        port: 8080

serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: true
    # -- Configures the endpoints for the serviceMonitor.
    # @default -- See values.yaml
    serviceName: navidrome-instance
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cf-issuer
    hosts:
      - host: music.magi.furst.blue
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              identifier: main
              port: 8080
    tls:
      - hosts:
          - music.magi.furst.blue
        secretName: navidrome-tls

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: freenas-iscsi-csi
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config

  media:
    type: nfs
    server: nas.furst.blue
    path: /mnt/pool1/music
    globalMounts:
      - path: /media
        readOnly: true
