controllers:
  main:
    pod:
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   fsGroup: 2000
      #   fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.52.5
        env:
          TZ: Europe/Berlin
          ND_AUTHREQUESTLIMIT: 0
          ND_DATAFOLDER: /config
          ND_ENABLEGRAVATAR: true
          ND_ENABLESHARING: true
          ND_LOGLEVEL: info
          ND_MUSICFOLDER: /media
          ND_PORT: 8080
          ND_PROMETHEUS_ENABLED: true
          ND_SCANSCHEDULE: "@every 1h"
        envFrom:
          - secretRef:
              name: navidrome-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 4533
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
service:
  main:
    ports:
      http:
        port: 4533
    monitor:
      # -- Enables or disables the serviceMonitor.
      enabled: true
      # -- Configures the endpoints for the serviceMonitor.
      # @default -- See values.yaml
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cf-issuer
    hosts:
      - host: music.magi.furst.blue
    tls:
      - hosts:
          - music.magi.furst.blue
        secretName: navidrome-tls

persistence:
  config:
    enabled: false

  media:
    enabled: false
