apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoria-metrics-operator

helmCharts:
- name: prometheus-operator-crds
  repo: oci://ghcr.io/prometheus-community/charts/
  version: "29.0.0"
  releaseName: prometheus-operator-crds
  namespace: victoria-metrics-operator
  valuesFile: values.yaml
