apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: democratic-csi

helmCharts:
- name: democratic-csi
  repo: https://democratic-csi.github.io/charts/
  version: 0.15.0
  releaseName: democratic-csi-nfs
  namespace: democratic-csi
  valuesFile: values.yaml
