global:
  domain: argocd.magi.furst.blue

configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
  params:
    server.insecure: true

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cf-issuer
    extraTls:
      - hosts:
        - argocd.magi.furst.blue
        secretName: argocd-tls
  httproute:
    # -- Enable HTTPRoute resource for Argo CD server (Gateway API)
    enabled: true
    # -- Additional HTTPRoute labels
    labels: {}
    # -- Additional HTTPRoute annotations
    annotations: {}
    # -- Gateway API parentRefs for the HTTPRoute
    ## Must reference an existing Gateway
    # @default -- `[]` (See [values.yaml])
    parentRefs:
      - group: gateway.networking.k8s.io	
        kind: Gateway
        name: default-gateway
        namespace: gateway
      #   sectionName: https
    # -- List of hostnames for the HTTPRoute
    # @default -- `[]` (See [values.yaml])
    hostnames:
      - "argocd.gw.furst.blue"

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
