---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-kustomize
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: kustomize/**
        pathParamPrefix: kustomize
        repoURL: git@github.com:furstblumier/k8s-setup.git
        revision: main
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{kustomize.path.basename}}"
    spec:
      destination: 
        server: "https://kubernetes.default.svc"
      project: default
      source:
        path: "{{kustomize.path}}"
        repoURL: git@github.com:furstblumier/k8s-setup.git
        targetRevision: main
        # enable this in argocd to be able to use vault
        # plugin:
        #   name: argocd-vault-plugin-helm-kustomize
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ServerSideApply=true

