apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io 
  version: v1.19.0
  releaseName: cert-manager-instance
  valuesFile: values.yaml
  includeCRDs: true
  namespace: cert-manager
