apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pingvin

helmCharts:
- name: pingvin-share-x
  releaseName: pingvin-share-x
  repo: https://viyi.github.io/pingvin-share-x/
  version: 1.0.5
  valuesFile: values.yaml
  namespace: pingvin

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingvin-logo-assets
  files:
    - logo-assets/logo.png
    - logo-assets/logo-dark.png
    - logo-assets/favicon.ico
    - logo-assets/icon-48x48.png
    - logo-assets/icon-72x72.png
    - logo-assets/icon-96x96.png
    - logo-assets/icon-128x128.png
    - logo-assets/icon-144x144.png
    - logo-assets/icon-152x152.png
    - logo-assets/icon-192x192.png
    - logo-assets/icon-384x384.png
    - logo-assets/icon-512x512.png

patches:
- target:
    kind: (ServiceAccount|Secret|Service|PersistentVolumeClaim|Deployment|HTTPRoute|Pod)
  patch: |-
    - op: add
      path: /metadata/namespace
      value: pingvin
- target:
    group: gateway.networking.k8s.io
    version: v1
    kind: HTTPRoute
    name: pingvin-share-x
  patch: |-
    - op: add
      path: /spec/rules/0/backendRefs/0/group
      value: ""
    - op: add
      path: /spec/rules/0/backendRefs/0/kind
      value: Service
