config:
  enabled: true
  inline:
    general:
      appUrl: "https://dl.furst.blue"
    share:
      allowRegistration: "false"
    oauth:
      allowRegistration: "false"
  useDefault: true

env:
  TRUST_PROXY: "true"

persistence:
  enabled: true
  storageClass: freenas-nfs-csi
  accessMode: ReadWriteOnce
  size: 100Gi

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
      namespace: gateway
  hostnames:
    - dl.furst.blue
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
