apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intel-device-plugins

helmCharts:
- name: intel-device-plugins-gpu
  repo: https://intel.github.io/helm-charts/
  version: 0.32.1
  releaseName: intel-device-plugin-gpu-instance
  valuesFile: values.yaml
  namespace: intel-device-plugins
