apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-env
  namespace: qbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: gluetun-env

  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: VPN_SERVICE_PROVIDER
    - secretKey: VPN_TYPE
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: VPN_TYPE
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: WIREGUARD_ENDPOINT_IP
    - secretKey: WIREGUARD_ENDPOINT_PORT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: WIREGUARD_ENDPOINT_PORT
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: WIREGUARD_PUBLIC_KEY
    - secretKey: FIREWALL_VPN_INPUT_PORTS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: FIREWALL_VPN_INPUT_PORTS
    - secretKey: FIREWALL_INPUT_PORTS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: FIREWALL_INPUT_PORTS

