apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: immich-postgres-user
    template:
      engineVersion: v2
      data:
        username: immich
        password: "{{ .password }}"
        

  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: IMMICH_DB_SECRET
