controllers:
  main:
    pod: {}
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   fsGroup: 2000
      #   fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: ghcr.io/hotio/unpackerr
          tag: release-0.14.5
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/Berlin
          UN_SONARR_0_URL: http://sonarr-instance.sonarr:8989
          UN_SONARR_0_API_KEY: fe55ca100cae469da47da1400c9dae9e
          UN_SONARR_0_PATHS_0: "/media/downloads"
          UN_SONARR_1_URL: http://sonarr-anime-instance.sonarr:8989
          UN_SONARR_1_API_KEY: 72d09e750b6246229e68d0ccec0fe070
          UN_SONARR_1_PATHS_0: "/media/downloads"
          UN_RADARR_0_URL: http://radarr-instance.radarr:7878
          UN_RADARR_0_API_KEY: 5edfa0ac433c40aaae4056f61dc86766
          UN_RADARR_0_PATHS_0: "/media/downloads"
          UN_LIDARR_0_URL: http://lidarr-instance.lidarr:8686
          UN_LIDARR_0_API_KEY: b584dfc1c62e445fa5b79058dcaa18a4
          UN_LIDARR_0_PATHS_0: "/media/downloads"
persistence:
  config:
    type: persistentVolumeClaim
    suffix: config
    storageClass: freenas-iscsi-csi
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

  media:
    type: nfs
    server: nas.furst.blue
    path: /mnt/pool1/media
    globalMounts:
      - path: /media
