apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-nfs-secret
  namespace: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api 
  target:
    name: democratic-csi-nfs-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          # please see the most up-to-date example of the corresponding config here:
          # https://github.com/democratic-csi/democratic-csi/tree/master/examples
          # YOU MUST COPY THE DATA HERE INLINE!
          driver: freenas-api-nfs
          instance_id:
          httpConnection:
            protocol: http
            host: nas.furst.blue
            port: 80
            # use only 1 of apiKey or username/password
            # if both are present, apiKey is preferred
            # apiKey is only available starting in TrueNAS-12
            apiKey: {{ .apitoken }}
            # username: root
            # password:
            allowInsecure: true
            # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
            # leave unset for auto-detection
            apiVersion: 2
          zfs:
            # can be used to override defaults if necessary
            # the example below is useful for TrueNAS 12
            # cli:
            #   sudoEnabled: true
            #
            #  leave paths unset for auto-detection
            #  paths:
            #    zfs: /usr/local/sbin/zfs
            #    zpool: /usr/local/sbin/zpool
            #    sudo: /usr/local/bin/sudo
            #    chroot: /usr/sbin/chroot
            
            # can be used to set arbitrary values on the dataset/zvol
            # can use handlebars templates with the parameters from the storage class/CO
            #datasetProperties:

            datasetParentName: pool1/k8s/nfs/vols
            # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
            # they may be siblings, but neither should be nested in the other
            # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
            detachedSnapshotsDatasetParentName: pool1/k8s/nfs/snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0

            # not supported yet
            #datasetPermissionsAcls:
            #- "-m everyone@:full_set:allow"
            #- "-m u:kube:full_set:allow"

          nfs:
            shareHost: nas.furst.blue
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks: []
            shareMaprootUser: root
            shareMaprootGroup: root
            shareMapallUser: "root"
            shareMapallGroup: "root"
  data:
    - secretKey: apitoken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: TRUENAS_API
