apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-gh-token
  namespace: arc-runners
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: arc-gh-token

  data:
    - secretKey: github_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: ARC_GITHUB_TOKEN

