apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

configMapGenerator:
- name: blocky
  files:
    - config.yml
generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: app-template
  releaseName: blocky-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.1.2
  valuesFile: values.yaml
