controllers:
  main:
    pod:
      nodeSelector:
        role: media
      
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   fsGroup: 2000
      #   fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/jellyfin
          tag: 2021.12.16
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/Berlin
          DOCKER_MODS: ghcr.io/intro-skipper/intro-skipper-docker-mod
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 8096
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        resources:
          limits:
            gpu.intel.com/i915: 1

service:
  main:
    controller: main
    ports:
      http:
        port: 8096

serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: true
    # -- Configures the endpoints for the serviceMonitor.
    # @default -- See values.yaml
    serviceName: jellyfin
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cf-issuer
    hosts:
      - host: jellyfin.magi.furst.blue
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              identifier: main
              port: 8096
    tls:
      - hosts:
          - jellyfin.magi.furst.blue
        secretName: jellyfin-tls

persistence:
  config:
    type: persistentVolumeClaim
    suffix: config
    storageClass: freenas-iscsi-csi
    accessMode: ReadWriteOnce
    size: 50Gi
    globalMounts:
      - path: /config

  media:
    type: nfs
    server: nas.furst.blue
    path: /mnt/pool1/media
    globalMounts:
      - path: /media
        readOnly: true
  
  homevideos:
    type: nfs
    server: nas.furst.blue
    path: /mnt/pool1/papa/videos
    globalMounts:
      - path: /homevideos
        readOnly: true
