apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photoprism

helmCharts:
- name: app-template
  releaseName: photoprism-mama
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.1.2
  valuesFile: values.yaml
  namespace: photoprism
