controllers:
  main:
    pod: {}
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   fsGroup: 2000
      #   fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/syncthing
          tag: 1.29.7
        env:
          TZ: Europe/Berlin
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /rest/noauth/health
                port: 8384
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
service:
  main:
    controller: main
    ports:
      http:
        port: 8384
  syncthing:
    controller: main
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: "192.168.176.17"
      lbipam.cilium.io/sharing-key: "default"
      lbipam.cilium.io/sharing-cross-namespace: "*"
    ports:
      sync-tcp:
        enabled: true
        port: 22000
        protocol: TCP
      sync-udp:
        enabled: true
        port: 22000
        protocol: UDP
      discovery:
        enabled: true
        port: 21027
        protocol: UDP


serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: true
    # -- Configures the endpoints for the serviceMonitor.
    # @default -- See values.yaml
    serviceName: syncthing-instance
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cf-issuer
    hosts:
      - host: sync.magi.furst.blue
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              identifier: main
              port: 8384
    tls:
      - hosts:
          - sync.magi.furst.blue
        secretName: syncthing-tls

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: freenas-nfs-csi
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

  media:
    type: nfs
    server: nas.furst.blue
    path: /mnt/pool1/syncthing
    globalMounts:
      - path: /data
        readOnly: false
