controllers:
  main:
    pod: {}
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   fsGroup: 2000
      #   fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-machine-learning
          tag: v1.129.0
        resources:
          requests:
            cpu: 15m
            memory: 250Mi
          limits:
            memory: 4000Mi
        env:
          TZ: Europe/Berlin
          TRANSFORMERS_CACHE: /cache
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 3003
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 3003
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 60
service:
  main:
    controller: main
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 3003
        protocol: HTTP

persistence:
  cache:
    enabled: true
    size: 10Gi
    # Optional: Set this to pvc to avoid downloading the ML models every start.
    type: persistentVolumeClaim
    storageClass: freenas-iscsi-csi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /cache
