apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blocky-pg-cluster
  namespace: dns
spec:
  instances: 2
  bootstrap:
    initdb:
      database: blocky
      owner: blocky
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "32MB"
      effective_cache_size: "96MB"
      maintenance_work_mem: "8MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "983kB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "300"
      work_mem: "81kB"
      huge_pages: "off"
      max_wal_size: "1GB"
  storage:
    size: 1Gi
    storageClass: freenas-iscsi-csi
