apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: photoprism
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: mariadb-root

  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: PHOTOPRISM_DB_ROOT_PW

