apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

helmCharts:
- name: app-template
  releaseName: jellyfin-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.1.2
  valuesFile: values.yaml
  namespace: jellyfin
