apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb-system

helmCharts:
- name: mariadb-operator
  repo: "https://helm.mariadb.com/mariadb-operator"
  version: "26.6.0"
  releaseName: mariadb-operator
  namespace: mariadb-system
  valuesFile: values.yaml

patches:
- target:
    kind: (ConfigMap|ServiceAccount|Deployment|ServiceMonitor|Role|RoleBinding|Service|Certificate|Issuer)
  patch: |-
    - op: add
      path: /metadata/namespace
      value: mariadb-system
