apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb-system

helmCharts:
- name: mariadb-operator
  repo: "https://helm.mariadb.com/mariadb-operator"
  version: "0.38.1"
  releaseName: mariadb-operator
  namespace: mariadb-system
  valuesFile: values.yaml
