apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

helmCharts:
- name: app-template
  releaseName: homeassistant-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.3.0
  valuesFile: values.yaml
  namespace: home-assistant
