---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-helm
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: helm/**/chart.yaml
        pathParamPrefix: helm
        repoURL: 'git@github.com:furstblumier/k8s-setup.git'
        revision: main
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{helm.path.basename}}'
    spec:
      destination:
        namespace: '{{chart.namespace}}'
        server: "https://kubernetes.default.svc"

      project: default
      sources:
        - chart: '{{chart.name}}'
          repoURL: '{{chart.repoURL}}'
          targetRevision: '{{chart.targetRevision}}'
          helm:
            valueFiles:
            - $values/helm/{{helm.path.basename}}/values.yaml
        - repoURL: 'git@github.com:furstblumier/k8s-setup.git'
          targetRevision: main
          ref: values
        # enable this in argocd to be able to use vault
        # plugin:
        #   name: argocd-vault-plugin-helm
        #   env:
        #     - name: HELM_VALUES
        #       value: '{{values}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ServerSideApply=true

