initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
## and additional server settings.
##
configuration:
  # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
  # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
  - name: "default"
    # provider is the name for the backup storage location provider.
    provider: "aws"
    # bucket is the name of the bucket to store backups in. Required.
    bucket: "velero"
    # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
    # caCert:
    # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
    # prefix:
    # default indicates this location is the default backup storage location. Optional.
    # default: false
    # validationFrequency defines how frequently Velero should validate the object storage. Optional.
    # validationFrequency:
    # accessMode determines if velero can write to this backup storage location. Optional.
    # default to ReadWrite, ReadOnly is used during migrations and restores.
    # accessMode: ReadWrite
    credential:
      # name of the secret used by this backupStorageLocation.
      name: minio-secret
      # name of key that contains the secret data to be used.
      key:
    # Additional provider-specific configuration. See link above
    # for details of required/optional fields for your provider.
    config:
      region: "minio"
      s3ForcePathStyle: true
      s3Url: "https://nas.furst.blue:9000"
