serviceAccount:
  create: true
 
rbac:
  create: true
 
apiService:
  create: true
 
priorityClassName: system-cluster-critical
 
hostNetwork:
  enabled: false
 
replicas: 2
 
revisionHistoryLimit: 0
 
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
 
podDisruptionBudget:
  enabled: true
  minAvailable: 1
 
addonResizer:
  enabled: false
 
metrics:
  enabled: true
 
serviceMonitor:
  enabled: true
  additionalLabels: {}
  interval: 1m
  scrapeTimeout: 10s
  metricRelabelings: []
  relabelings: []
 
resources:
  requests:
    cpu: 100m
    memory: 200Mi
    # limits:
    #   cpu:
    #   memory:
 
affinity: {}
 
topologySpreadConstraints: []
 
dnsConfig: {}
 
tls:
  type: "cert-manager"
 
  certManager:
    addInjectorAnnotations: true
 
  helm:
    lookup: false
 
  existingSecret:
    lookup: false

