apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-mail
  namespace: mail
spec:
  secretName: mail-crt-secret
  dnsNames:
    - k8s-mail.magi.furst.blue
    - imap.magi.furst.blue
    - smtp.magi.furst.blue
    - imap.furst.blue
    - smtp.furst.blue
  issuerRef:
    name: cf-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
