apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cf-issuer
spec:
  acme:
    email: seal@furst.blue
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: acme-issuer-account-key
    solvers:
    - selector:
        dnsZones:
        - "k8s.furst.blue"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
